blog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings 
from rest_framework_jwt.views import obtain_jwt_token
from accounts.views import *

urlpatterns = [
    # Examples:
    # url(r'^$', 'blog.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^comments/', include("comments.urls", namespace="comments")),
    url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^profile/', profile_view, name='profile'),
    url(r'^register/', register_view, name='register'),
    url(r'^api/auth/token/', obtain_jwt_token),
    url(r'^api/users/', include("accounts.api.urls", namespace="users-api")),
    url(r'^api/comments/', include("comments.api.urls", namespace="comments-api")),
    url(r'^api/posts/', include("posts.api.urls", namespace="posts-api")),
    url(r'^', include("posts.urls", namespace="posts")),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

posts/api/urls.py
from django.conf.urls import url

from .views import PostListAPIView, PostDetailAPIView, PostUpdateAPIView, PostDeleteAPIView, PostCreateAPIView

urlpatterns = [
    url(r'^$', PostListAPIView.as_view(), name="list"),
    url(r'^create/$', PostCreateAPIView.as_view() , name="add_post"),
    url(r'^(?P<slug>[\w-]+)/$', PostDetailAPIView.as_view(), name="detail"),
    # url(r'^about/$', about, name="about"),
    url(r'^(?P<slug>[\w-]+)/edit/$', PostUpdateAPIView.as_view() , name="update"),
    url(r'^(?P<slug>[\w-]+)/delete/$', PostDeleteAPIView.as_view() , name="delete"),
]

posts/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from .views import *

urlpatterns = [
    url(r'^$', post_list, name="list"),
    url(r'^about/$', about, name="about"),
    url(r'^create/$', post_create, name="add_post"),
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name="detail"),
    url(r'^(?P<slug>[\w-]+)/edit/$', post_update, name="update"),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete, name="delete"),
]

trydjango19/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings 

urlpatterns = [
    # Examples:
    # url(r'^$', 'trydjango19.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^post/', include("posts.urls", namespace="posts")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

posts/models.py
from __future__ import unicode_literals
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.utils.text import slugify
from django.utils.safestring import mark_safe
from markdown_deux import markdown
from comments.models import Comment
from django.contrib.contenttypes.models import ContentType
from .utils import get_read_time
# Create your models here.


class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())


def upload_location(instance, filename):
    return "%s" %(filename)

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to=upload_location, null=True, blank=True, width_field="width_field", height_field="height_field")
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    content = models.TextField()
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    read_time = models.IntegerField(default=0) # models.TimeField(null=True, blank=True)

    objects = PostManager()

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    def get_markdown(self):
        content = self.content 
        return mark_safe(markdown(content))

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"slug": self.slug})

    def get_api_url(self):
        return reverse("posts-api:detail", kwargs={"slug": self.slug})

    def get_delete_url(self):
        return reverse("posts:delete", kwargs={"slug": self.slug})

    def get_edit_url(self):
        return reverse("posts:update", kwargs={"slug": self.slug})

    @property
    def comments(self):
        qs = Comment.objects.filter_by_instance(self)
        return qs

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type

    class Meta():
        ordering = ["-timestamp", "-updated"]


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug)
    return slug



def pre_save_post_reciever(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)
    if instance.content:
        html_string = instance.get_markdown()
        read_time = get_read_time(html_string)
        instance.read_time = read_time


pre_save.connect(pre_save_post_reciever, sender=Post)

posts/forms.py
from django import forms

from pagedown.widgets import PagedownWidget
from .models import Post


class PostForm(forms.ModelForm):
    content = forms.CharField(widget=PagedownWidget(show_preview=False))
    publish = forms.DateField(widget=forms.SelectDateWidget)
    class Meta:
        model = Post
        fields = [
            "title",
            "image",
            "content",
            "draft",
            "publish"
        ]
        

posts/api/views.py
from rest_framework.generics import ListAPIView, RetrieveAPIView, RetrieveUpdateAPIView, DestroyAPIView, CreateAPIView
from rest_framework.permissions import AllowAny, IsAuthenticated, IsAdminUser, IsAuthenticatedOrReadOnly
from rest_framework.filters import SearchFilter, OrderingFilter
from .permissions import IsOwnerOrReadOnly
from django.db.models import Q
from posts.models import Post
from .serializers import *
from .pagination import *


class PostCreateAPIView(CreateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostCreateUpdateSerializer
    # permission_classes = [IsAuthenticated]

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)



class PostListAPIView(ListAPIView):
    serializer_class = PostListSerializer
    filter_backends = [SearchFilter, OrderingFilter]    # ?search= and ?ordering=
    search_fields = ['title', 'content', 'user__first_name']
    pagination_class = PostPageNumberPagination # PostLimitOffsetPagination # PageNumberPagination
    permission_classes = [AllowAny]

    def get_queryset(self, *args, **kwargs):
        queryset_list = Post.objects.all()
        query = self.request.GET.get("q")
        if query:
            queryset_list = queryset_list.filter(
                    Q(title__icontains=query)|
                    Q(content__icontains=query)|
                    Q(user__first_name__icontains=query)|
                    Q(user__last_name__icontains=query)
                ).distinct()
        return queryset_list



class PostUpdateAPIView(RetrieveUpdateAPIView):
    queryset = Post.objects.all()
    lookup_field = 'slug'
    serializer_class = PostCreateUpdateSerializer
    permission_classes = [IsOwnerOrReadOnly]

    def perform_update(self, serializer):
        serializer.save(user=self.request.user)



class PostDeleteAPIView(DestroyAPIView):
    queryset = Post.objects.all()
    lookup_field = 'slug'
    serializer_class = PostDetailSerializer
    permission_classes = [IsOwnerOrReadOnly]



class PostDetailAPIView(RetrieveAPIView):
    queryset = Post.objects.all()
    lookup_field = 'slug'
    serializer_class = PostDetailSerializer
    permission_classes = [AllowAny]

posts/views.py
try:
    from urllib import quote_plus
except:
    from urllib.parse import quote_plus
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils import timezone
from django.db.models import Q
from .forms import PostForm
from .models import Post
from comments.models import Comment
from comments.forms import CommentForm
from django.contrib.contenttypes.models import ContentType


@login_required
def post_create(request):
    # if not request.user.is_staff or not request.user.is_superuser:
    #     raise Http404
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        messages.success(request, "Successfully Posted", extra_tags="alert-success")
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        "title": "Add Post",
        "form": form
    }
    return render(request, "post_form.html", context)


def post_detail(request, slug=None):
    instance = get_object_or_404(Post, slug=slug)
    share_string = quote_plus(instance.content)
    comments = instance.comments
    initial_data = {
        "content_type": instance.get_content_type,
        "object_id": instance.id
    }
    comment_form = CommentForm(request.POST or None, initial=initial_data)
    if comment_form.is_valid() and request.user.is_authenticated():
        c_type = comment_form.cleaned_data.get('content_type')
        content_type = ContentType.objects.get(model=c_type)
        obj_id = comment_form.cleaned_data.get('object_id')
        content_data = comment_form.cleaned_data.get('content')
        parent_obj = None
        try:
            parent_id = int(request.POST.get("parent_id"))
        except:
            parent_id = None
        if parent_id:
            parent_qs = Comment.objects.filter(id=parent_id)
            if parent_qs.exists() and parent_qs.count() == 1:
                parent_obj = parent_qs.first()
        new_comment, created = Comment.objects.get_or_create(user=request.user, content_type=content_type, object_id=obj_id, content=content_data, parent=parent_obj)
        return HttpResponseRedirect(new_comment.content_object.get_absolute_url())
    context = {
        "title": instance.title,
        "instance": instance,
        "share_string": share_string,
        "comments": comments,
        "form": comment_form
    }
    return render(request, "post_detail.html", context)


def post_list(request):
    queryset_list = Post.objects.active()
    if request.user.is_staff or request.user.is_superuser:
        queryset_list = Post.objects.all()

    query = request.GET.get('q')
    if query:
        queryset_list = queryset_list.filter(
                Q(title__icontains=query)|
                Q(content__icontains=query)|
                Q(user__first_name__icontains=query)|
                Q(user__last_name__icontains=query)
            ).distinct()
        
    paginator = Paginator(queryset_list, 5)
    page = request.GET.get('page')
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        queryset = paginator.page(1)
    except EmptyPage:
        queryset = paginator.page(paginator.num_pages)
    context = {
        "object_list": queryset,
        "title": "Blog"
    }
    return render(request, "post_list.html", context)


def post_update(request, slug=None):
    instance = get_object_or_404(Post, slug=slug)
    if instance.draft or instance.publish > timezone.now().date():
        if not request.user.is_staff or not request.user.is_superuser:
            raise Http404
    form = PostForm(request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "Saved Changes", extra_tags="alert-success")
        return HttpResponseRedirect(instance.get_absolute_url())

    context = {
        "title": instance.title,
        "instance": instance,
        "form": form
    }
    return render(request, "post_form.html", context)


def post_delete(request, slug=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, slug=slug)
    instance.delete()
    messages.success(request, "Successfully Deleted", extra_tags="alert-success")
    return redirect("posts:list")



def about(request):
    context = {
        "post_count": Post.objects.count(),
        "title": "About"
    }
    return render(request, "about.html", context)

templates/about.html
{% extends "base.html" %}


{% block title %}{{ title }} | {{ block.super }}{% endblock %}

{% block content %}
<p class="post_count">Total Number of Posts in this site:  <strong>{{ post_count }}</strong></p>
<br>
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</div>

    <footer class="footer">
      <div class="container">
        <span class="text-muted">Copyright &copy; 2017 blog</span>
      </div>
    </footer>
<!--/Footer-->
{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    
    <!-- CDN -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,500,700i" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="http://getbootstrap.com/docs/3.3/examples/sticky-footer-navbar/sticky-footer-navbar.css">
    <!-- <link rel="stylesheet" type="text/css" href="https://raw.githubusercontent.com/Shubh-Sharma/blog/master/static/css/style.css"> -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    
    <title>{% block title %}try django 1.9{% endblock %}</title>

    {% block head %} {% endblock %}
</head>
<body>
    <div id="fb-root"></div>
    <script>
    (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
    </script>
    {% include "snippets/navbar.html" %}
    {% include "snippets/messages_display.html" %}
    <div class="container">
    {% block content %}
    {% endblock %}
    </div>


    <!-- CDN -->
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.7/marked.min.js"></script>

    <script>
    $(document).ready(function(){
        $(".content-markdown").each(function(){
            var content = $(this).text()
            var markedContent = marked(content)
            $(this).html(markedContent)
        })
        $(".post-detail-item img").each(function(){
            $(this).addClass("img-responsive")
        })
    })

    var titleItem = $("#id_title")
    $("#preview-title").text(titleItem.val())

    var contentItem = $("#id_content")

    function setContent(value){
        var markedContent = marked(value)
        $("#preview-content").html(markedContent)
        $("#preview-content img").each(function(){
            $(this).addClass("img-responsive")
        })
    }

    function setTitle(value){
        $("#preview-title").text(value)
    }

    titleItem.keyup(function(){
        setTitle(titleItem.val())
    })

    contentItem.keyup(function(){
        setContent(contentItem.val())
    })

    $(".comment-reply-btn").click(function(event){
        event.preventDefault();
        $(this).parent().next(".comment-replies").fadeToggle();
    })
    </script>
</body>
</html>

templates/comment-thread.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load urlify %}

{% block title %}{{ title }} | {{ block.super }}{% endblock %}

{% block content %}
<div class="col-sm-6 col-sm-offset-3">
    <div class="well">
        <p class="lead" style="float: left;">{{ comment.content }}</p>{% if request.user == comment.user %}<a href="{{ comment.get_delete_url }}" style="float: right;" class="text-danger">Delete thread</a>{% endif %}
        <div class="clear-fix" style="clear: both;"></div>
        <div class="text-muted">via {{ comment.user }} | {{ comment.timestamp|timesince }} ago | {% if comment.children.count > 0 %} {{ comment.children.count }} Comment{% if comment.children.count > 1 %}s{% endif %} {% endif %}</div>
        {% for child_comment in comment.children %}
            <blockquote class="blockquote">
                <p>{{ child_comment.content }}</p>
                <footer>via {{ child_comment.user }} {{ child_comment.timestamp|timesince }} ago | {% if request.user == child_comment.user %}<a href="{{ child_comment.get_delete_url }}" class="text-danger">Delete comment</a>{% endif %}</footer>
            </blockquote>
        {% endfor %}
        {% if request.user.is_authenticated %}
            <form method="POST" action=".">{% csrf_token %}
                {{ form|crispy }}
                <input type="hidden" name="parent_id" value="{{ comment.id }}">
                <input type="submit" value="Reply" class="btn btn-default">
            </form>
        {% else %}
            <p>You must <a href="{% url 'login' %}">login</a> to comment.</p>
        {% endif %}
        
    </div>
</div>
{% endblock %}

templates/confirm-delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load urlify %}

{% block title %}{{ title }} | {{ block.super }}{% endblock %}

{% block content %}
<div class="col-sm-6 col-sm-offset-3 text-center">
    <div class="well">
        <h1>Confirm Delete?</h1>
        <form action="." method="POST">{% csrf_token %}
            <p class="lead">Are you sure you want to delete "{{ object.content }}"?</p>
            <input type="submit" value="Confirm" class="btn btn-danger">
            <a href="{{ object.get_absolute_url }}" class="btn btn-warning">Cancel</a>
        </form>
    </div>
</div>
{% endblock %}

templates/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}

<div class="col-sm-4 col-sm-offset-4 text-center">

    {% if not request.user.is_authenticated %}
        <div class="well well-sm">
            <h1>{{ title|capfirst }}</h1>
            <hr>
            <form class="form" method="POST">{% csrf_token %}
                {{ form|crispy }}
                <input class="btn btn-primary" type="submit" value="{{ title|capfirst }}" name="{{ title }}">
            </form>
            <hr>
            {% if title == "login" %}
                <p>New user? <a href="{% url 'register' %}">Register here</a></p>
            {% else %}
                <p>Already registered? <a href="{% url 'login' %}">Login here</a></p>
            {% endif %}
        </div>

    {% else %}
        <div class="well well-sm text-center">
            <p>You are already logged in as {{ request.user.username }}.</p>
            <p>Do you want to <a href="{% url 'logout' %}">logout</a>?</p>
        </div>
    {% endif %}
    
</div>

{% endblock %}

templates/post_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load urlify %}

{% block title %}{{ title }} | {{ block.super }}{% endblock %}

{% block content %}
<div class="col-sm-6 col-sm-offset-3">
    {% if instance.image %}<img src="{{ instance.image.url}}" class="img-responsive"> {% endif %}
    <h1>{{ instance.title }} {% if instance.draft %}
        <span class="badge">Draft</span>
    {% endif %}<small class="post_date">{{ instance.publish }}</small></h1>
    <p><small class="text-muted">Read time: {% if instance.read_time <= 1%} less than a minute {% else %} {{ instance.read_time }} minute{% if instance.read_time > 1%}s{% endif %}{% endif %}</small></p>
    {% if instance.user.get_full_name %}
    <p>Author: {{ instance.user.get_full_name }}</p>
    {% endif %}

    <!-- SHARE LINKS 
    <p>
        <a style="margin-right: 20px;" href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">
        <i class="fa fa-facebook-square fa-3x" aria-hidden="true"></i>
        </a>

        <a style="margin-right: 20px;" href="https://twitter.com/home?status={{ instance.content|urlify }}%20{{ request.build_absolute_uri }}">
        <i class="fa fa-twitter-square fa-3x" aria-hidden="true"></i>
        </a>

        <a style="margin-right: 20px;" href='https://plus.google.com/share?url={{ request.build_absolute_uri }}'><i class="fa fa-google-plus-square fa-3x" aria-hidden="true"></i></a>

        <a style="margin-right: 20px;" href="https://www.linkedin.com/shareArticle?mini=true&url={{ request.build_absolute_uri }}&title={{ instance.title }}&summary={{ instance.content|urlify }}&source={{ request.build_absolute_uri }}">
        <i class="fa fa-linkedin-square fa-3x" aria-hidden="true"></i>
        </a>


        <a href="http://www.reddit.com/submit?url={{ request.build_absolute_uri }}&title={{ instance.content|urlify }}."><i class="fa fa-reddit-square fa-3x" aria-hidden="true"></i></a>
        
    </p>
     SHARE LINKS END -->
     <div class="post-detail-item">
    {{ instance.get_markdown }}
    </div>
    <small class="text-muted">last updated {{ instance.updated|timesince }} ago</small>
    <p><div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div></p>

    <p class="lead">Comments</p>
        {% if request.user.is_authenticated %}
            <form method="POST" action=".">{% csrf_token %}
                {{ form|crispy }}
                <input type="submit" value="Comment" class="btn btn-default">
            </form>
        {% else %}
            <p>You must <a href="{% url 'login' %}">login</a> to comment.</p>
        {% endif %}
        
        <br>
    {% for comment in comments %}
    <div class="well well-sm">
        <blockquote class="blockquote">
            <p>{{ comment.content }}</p>
            <footer>via {{ comment.user }} | {{ comment.timestamp|timesince }} ago | {% if comment.children.count > 0 %} {{ comment.children.count }} Comment{% if comment.children.count > 1 %}s{% endif %} | {% endif %} <a href="#" class="comment-reply-btn">reply</a> | <a href="{{ comment.get_absolute_url }}">thread</a></footer>
            <div class="comment-replies">
                {% for child_comment in comment.children %}
                    <blockquote class="blockquote">
                        <p>{{ child_comment.content }}</p>
                        <footer>via {{ child_comment.user }} {{ child_comment.timestamp|timesince }} ago</footer>
                    </blockquote>
                {% endfor %}
                {% if request.user.is_authenticated %}
                    <form method="POST" action=".">{% csrf_token %}
                        {{ form|crispy }}
                        <input type="hidden" name="parent_id" value="{{ comment.id }}">
                        <input type="submit" value="Reply" class="btn btn-default">
                    </form>
                {% else %}
                    <p>You must <a href="{% url 'login' %}">login</a> to comment.</p>
                {% endif %}
            </div>
        </blockquote>
    </div>  
    {% endfor %}


    <!-- <div class="fb-comments" data-href="{{ request.build_absolute_uri }}" data-numposts="5"></div> -->
</div>

{% endblock %}

templates/post_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ title }} | {{ block.super }}{% endblock title %}

{% block head %}{{ form.media }}{% endblock %}

{% block content %}

<div class="col-sm-6">
    <h3>Create Post</h3>
    <hr>
    <form class="form" method="POST" enctype="multipart/form-data">{% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-default" type="submit" value="Create Post" name="create_post">
    </form>
</div>

<div class="col-sm-6">
    <h3>Preview</h3>
    <hr>
    <div class="content-preview">
        <h1 id="preview-title"></h1>
        <p id="preview-content"></p>
    </div>
</div>

{% endblock %}

templates/post_list.html
{% extends "base.html" %}

{% block title %}{{ title }} | {{ block.super }}{% endblock %}

{% block content %}

    <div class="col-sm-6 col-sm-offset-3">
        {% for obj in object_list %}
            <div class="row">
                <div class="col-sm-12">
                    <div class="thumbnail">
                        {% if obj.image %}<img src="{{ obj.image.url }}"> {% endif %}
                        <div class="caption post-detail-item">
                            <h3>{% if obj.draft %}<span class="badge">Draft</span>{% endif %}<a href="{{ obj.get_absolute_url }}">{{ obj.title }}</a> <small>{{ obj.publish }}</small></h3>
                            {% if obj.user.get_full_name %}
                                <p>Author: {{ obj.user.get_full_name }}</p>
                            {% endif %}
                            <p>{{ obj.get_markdown|truncatechars_html:30 }}</p>
                            <p><a href="{{ obj.get_absolute_url }}" class="btn btn-primary">View</a> {% if request.user.is_superuser  and request.user == obj.user %}<a href="{{ obj.get_edit_url }}" class="btn btn-default">Edit</a> <a href="{{ obj.get_delete_url }}" class="btn btn-danger">Delete</a>{% endif %}</p>
                        </div>
                    </div>
                </div>
                <hr>
            </div>
        {% endfor %}

<nav aria-label="paginator">
    <ul class="pager">
        {% if object_list.has_previous %}
            <li><a href="?page={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Previous</a></li>
        {% endif %}
        <li>Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}</li>
        {% if object_list.has_next %}
            <li><a href="?page={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Next</a></li>
        {% endif %}
    </ul>
</nav>


{% endblock %}

templates/profile.html
{% extends "base.html" %}


{% block title %}{{ title }} | {{ block.super }}{% endblock %}

{% block content %}

<p class="lead">Logged in as {{ title }}</p>
<a href="{% url 'logout' %}">Logout</a>
<footer class="footer">
  <div class="container">
    <span class="text-muted">Copyright &copy; 2017 blog</span>
  </div>
</footer>
<!--/Footer-->
{% endblock %}